### ISSUE TITLE
3rd party docker image prefix support conflicts with canonical kernel name

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-manager#117]
* 3rd party docker image prefix support conflicts with canonical kernel name
 * Therefore, kernel reuse is blocked.
 * Need to strip 3rd party docker image prefix for finer kernel name comparison.

**Comment by achimnol** [comment]
982526d5e97f907a31d893483d26de0db531fde5 is related to this issue actually, not #112....

**Comment by achimnol** [comment]
This is now completely resolved with explicit "known registries" contextual information attached to `ImageRef` instantiation.
