### ISSUE TITLE
BigInteger for GraphQL API

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-manager#133]
Currently, [graphene rejects to serialize integers bigger than 32-bit.](https://github.com/graphql-python/graphene/blob/master/graphene/types/scalars.py)
However, we have a lot of such big integers to represent memory size (multiple GiB) and storage size (multiple TiB).

The primary reason for graphene to limit integers in 32-bit range is to keep maximum compatibility with cross-platform javascript parsers. ([ref: FB's GraphQL GitHub discussion](https://github.com/facebook/graphql/issues/73))

We primarily target modern JS engines, which encodes numbers in the IEEE-754 floating point format that can store integers within the 53-bit range safely (without loosing accuracy or significant digits).
For example, the JS engines in Chrome/Firefox define `Number.MAX_SAFE_INTEGER` and `Number.MIN_SAFE_INTEGER` as 9007199254740991 and -9007199254740991 (which are approximately +-8192 TiB).

There are some choices:
 * Monkey-patch `MIN_INT` and `MAX_INT` values in the graphene library (`graphene.types.scalars`) at runtime -- which assumes we only use "modern" JS engines in the client-side
 * Write a custom scalar type that serializes big integers as strings -- which requires client-side changes as well
 * "Humanize" all big integers before sending to clients -- which makes clients to convert those back to raw numbers for arithematic (e.g., progress bar rendering)

Let's try the first option.

**Comment by achimnol** [comment]
Pre-check:
* [x] Python's json module serializes big integers as plain number literals without any errors.
* [x] Modern browsers define `Number.MAX_SAFE_INTEGER` and its value is 9007199254740991.
* [x] NodeJS defines `Number.MAX_SAFE_INTEGER` and its value is 9007199254740991.

ref) https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by achimnol** [comment]
Let's use `ai.backend.manager.models.base.BigInt` for big-integer fields in GQL from now on.

**Comment by amiri27** [comment]
FDTDAFDDFDASGWWE353ZZHCTFDD53ÁZZ
