### ISSUE TITLE
Inconsistent slot resource format

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-manager#136]
## Description

Value formats in slot resources (occupied_slots, available_slots) is inconsistent.

### Case 1
`occupied_slots: "{"cpu": "8", "mem": "64 GiB", "cuda.device": "1"}"`

### Case 2
`occupied_slots: "{"cpu": "1", "mem": "1g", "cuda.device": "0"}"`

### Case 3
`occupied_slots: "{"cpu": "1", "mem": "256 MiB", "cuda.device": "0"}"`

### Case 4
`occupied_slots: "{"cpu": "1", "mem": "256m", "cuda.device": "0"}"`

In JS library and GUI console, it is handled with handwritten fallback routine. (see https://github.com/lablup/backend.ai-console/commit/be5983903d33e712d11b6caaaa7857e826bb9f06 ) However, we need a polished solution / resource description rules to avoid duplicated dirty jobs.

**Comment by achimnol** [comment]
I can alway numericalize all numbers, but still it is the client's job to determine which field represents bytes or count. Also to handle big integers, all values are stringified.
Are you okay with this?

**Comment by achimnol** [comment]
This is now rewritten and resolved.
