### ISSUE TITLE
fix travis ci test error

### ISSUE THREAD

**Issue by Myeongjoon** [lablup/backend.ai-manager#190]
Hello.
I'm participating at 2019 contribution.
This repo seems has test error.
https://github.com/lablup/backend.ai-manager/runs/220837192
Can I contribute to this?

**Comment by achimnol** [comment]
Yes, but the most failing tests are due to code changes ("대격변"...), so fixing them would require you to understand the gory details.
First, please contribute to fixing up the CI environment setup and conftest.py's mismatched bits.
The we will be able to begin with individual modules.

**Comment by achimnol** [comment]
Now it's green again.
